import './globals.css'
// import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import Header from './common/header'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800']

})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Header /> */}
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
